### PR TITLE
[WIP] Boto3 + python3 upgrade

### PR DESCRIPTION
**Pull request by njb**
Hi Mark, Prem, Bryan,

As discussed in side conversations, the boto mturk-requester-api API that CAQE uses has been depreciated. This makes CAQE no longer functional. See https://blog.mturk.com/older-versions-of-the-mturk-requester-api-to-be-deprecated-beginning-june-1st-2019-9fcc9791fa18. The current version of CAQE also requires Python 2.

I've made a rough upgrade to boto3 and Python3 here. I've used this on two separate project (removed project specific code), so it is workable. That said, I did not completely test all CAQE functionality, etc., so we can just use this as a starting point.

Let the reviewing begin!

TODO:
* Make necessary updates to documentation that's slightly out of date.
* Post a list of test starts to verify changes work.

### CODE REVIEW

**Comment by pseeth** [comment]
Is this good to pull in? lgtm. Let me know if it's okay to use and I can pull it in!

**Comment by mcartwright** [comment]
@pseeth have you or @ethman confirmed these changes?

**Comment by csapot** [comment]
The Boto3 & Python3 branch works fine, I was able to test the general_mushra.cfg on the mturk sandbox.

**Comment by njb** [comment]
When I put this up in October, things worked. However, I only tested on a few different workflows that I was using. Without this, nothing will work guaranteed. With this, I think a few things should work, but there's likely a few more things to work through.

**Comment by interactiveaudiolab** [comment]
Since the current state of the main branch is is "it doesn't work at all" because it's in Python 2 and also written to work with a deprecated MTURK API, It seems like we should just do this.  It can't be worse and it might be better.

**Pull request merged**
